version: "3"

services:
  api:
    container_name: ctesf5_api
    image: registry.gitlab.com
    restart: always
    depends_on:
      - db
  app:
    container_name: ctesf5_app
    image: registry.gitlab.com
    restart: always
    depends_on:
      - api
  nginx:
    container_name: ctesf5_nginx
    image: registry.gitlab.com
    restart: always
    ports:
      - "8081:80"
    depends_on:
      - api
      - app
